import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Acetaminophen",
    price: 20,
    image: "/assets/images/shop/shopThumb1_1.jpg",
    category: "Medicine",
    rating: 5,
    status: "in stock",
    description: "Effective pain reliever and fever reducer. Acetaminophen is commonly used to treat mild to moderate pain and reduce fever.",
    reviews: [
      {
        id: "r1",
        name: "John Smith",
        date: "2024-02-20",
        rating: 5,
        comment: "Great product! Highly recommend.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
      },
    ],
  },
  {
    id: "2",
    name: "Ciprofloxacin",
    price: 25,
    image: "/assets/images/shop/shopThumb1_2.jpg",
    category: "Medicine",
    rating: 4,
    status: "in stock",
    description: "Broad-spectrum antibiotic used to treat bacterial infections. Effective against various types of bacteria.",
    reviews: [
      {
        id: "r2",
        name: "Sarah Johnson",
        date: "2024-02-18",
        rating: 4,
        comment: "Works well, very satisfied.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
      },
    ],
  },
  {
    id: "3",
    name: "Escitalopram",
    price: 30,
    image: "/assets/images/shop/shopThumb1_3.jpg",
    category: "Tablet",
    rating: 5,
    status: "in stock",
    description: "SSRI antidepressant used to treat depression and anxiety. Helps maintain chemical balance in the brain.",
    reviews: [
      {
        id: "r3",
        name: "Mike Davis",
        date: "2024-02-15",
        rating: 5,
        comment: "Excellent medication.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
      },
    ],
  },
  {
    id: "4",
    name: "Amlodipine",
    price: 18,
    image: "/assets/images/shop/shopThumb1_4.jpg",
    category: "Tablet",
    rating: 3,
    status: "out of stock",
    description: "Calcium channel blocker used to treat high blood pressure and chest pain. Helps relax blood vessels.",
    reviews: [
      {
        id: "r4",
        name: "Emily Brown",
        date: "2024-02-10",
        rating: 3,
        comment: "Average, works as expected.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
      },
    ],
  },
  {
    id: "5",
    name: "Ranitidine",
    price: 22,
    image: "/assets/images/shop/shopThumb1_5.jpg",
    category: "Capsule",
    rating: 4,
    status: "in stock",
    description: "H2 receptor antagonist that reduces stomach acid. Used for heartburn and ulcer treatment.",
    reviews: [
      {
        id: "r5",
        name: "Robert Wilson",
        date: "2024-02-08",
        rating: 4,
        comment: "Good value for money.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
      },
    ],
  },
  {
    id: "6",
    name: "Famotidine",
    price: 19,
    image: "/assets/images/shop/shopThumb1_6.jpg",
    category: "Capsule",
    rating: 5,
    status: "in stock",
    description: "Potent H2 receptor antagonist that reduces stomach acid production. Ideal for acid reflux relief.",
    reviews: [
      {
        id: "r6",
        name: "Lisa Anderson",
        date: "2024-02-05",
        rating: 5,
        comment: "Best product, very effective!",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
      },
    ],
  },
];