import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Acetaminophen",
    price: 20,
    image: "/assets/images/shop/shopThumb1_1.jpg",
    category: "Medicine",
    rating: 5,
    status: "in stock",
    description: "Effective pain reliever and fever reducer. Acetaminophen is commonly used to treat mild to moderate pain and reduce fever.",
    reviews: [
      {
        id: "r1",
        name: "John Smith",
        date: "2024-02-20",
        rating: 5,
        comment: "Great product! Highly recommend.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
      },
    ],
  },
  {
    id: "2",
    name: "Ciprofloxacin",
    price: 25,
    image: "/assets/images/shop/shopThumb1_2.jpg",
    category: "Medicine",
    rating: 4,
    status: "in stock",
    description: "Broad-spectrum antibiotic used to treat bacterial infections. Effective against various types of bacteria.",
    reviews: [
      {
        id: "r2",
        name: "Sarah Johnson",
        date: "2024-02-18",
        rating: 4,
        comment: "Works well, very satisfied.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
      },
    ],
  },
  {
    id: "3",
    name: "Escitalopram",
    price: 30,
    image: "/assets/images/shop/shopThumb1_3.jpg",
    category: "Tablet",
    rating: 5,
    status: "in stock",
    description: "SSRI antidepressant used to treat depression and anxiety. Helps maintain chemical balance in the brain.",
    reviews: [
      {
        id: "r3",
        name: "Mike Davis",
        date: "2024-02-15",
        rating: 5,
        comment: "Excellent medication.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
      },
    ],
  },
  {
    id: "4",
    name: "Amlodipine",
    price: 18,
    image: "/assets/images/shop/shopThumb1_4.jpg",
    category: "Tablet",
    rating: 3,
    status: "out of stock",
    description: "Calcium channel blocker used to treat high blood pressure and chest pain. Helps relax blood vessels.",
    reviews: [
      {
        id: "r4",
        name: "Emily Brown",
        date: "2024-02-10",
        rating: 3,
        comment: "Average, works as expected.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
      },
    ],
  },
  {
    id: "5",
    name: "Ranitidine",
    price: 22,
    image: "/assets/images/shop/shopThumb1_5.jpg",
    category: "Capsule",
    rating: 4,
    status: "in stock",
    description: "H2 receptor antagonist that reduces stomach acid. Used for heartburn and ulcer treatment.",
    reviews: [
      {
        id: "r5",
        name: "Robert Wilson",
        date: "2024-02-08",
        rating: 4,
        comment: "Good value for money.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
      },
    ],
  },
  {
    id: "6",
    name: "Famotidine",
    price: 19,
    image: "/assets/images/shop/shopThumb1_6.jpg",
    category: "Capsule",
    rating: 5,
    status: "in stock",
    description: "Potent H2 receptor antagonist that reduces stomach acid production. Ideal for acid reflux relief.",
    reviews: [
      {
        id: "r6",
        name: "Lisa Anderson",
        date: "2024-02-05",
        rating: 5,
        comment: "Best product, very effective!",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
      },
    ],
  },
  {
  id: "7",
  name: "Ibuprofen",
  price: 15,
  image: "/assets/images/shop/shopThumb1_7.jpg",
  category: "Tablet",
  rating: 4,
  status: "in stock",
  description: "Nonsteroidal anti-inflammatory drug used to relieve pain, inflammation, and fever.",
  reviews: [
    {
      id: "r7",
      name: "Daniel Moore",
      date: "2024-02-04",
      rating: 4,
      comment: "Very effective for headaches.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
    },
  ],
},
{
  id: "8",
  name: "Metformin",
  price: 28,
  image: "/assets/images/shop/shopThumb1_8.jpg",
  category: "Tablet",
  rating: 5,
  status: "in stock",
  description: "Common medication used to improve blood sugar control in type 2 diabetes.",
  reviews: [
    {
      id: "r8",
      name: "Grace Lee",
      date: "2024-02-03",
      rating: 5,
      comment: "Works perfectly for my needs.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
    },
  ],
},
{
  id: "9",
  name: "Amoxicillin",
  price: 24,
  image: "/assets/images/shop/shopThumb1_9.jpg",
  category: "Capsule",
  rating: 4,
  status: "in stock",
  description: "Penicillin antibiotic used to treat bacterial infections.",
  reviews: [
    {
      id: "r9",
      name: "Kevin White",
      date: "2024-02-02",
      rating: 4,
      comment: "Cleared my infection quickly.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin",
    },
  ],
},
{
  id: "10",
  name: "Azithromycin",
  price: 32,
  image: "/assets/images/shop/shopThumb1_10.jpg",
  category: "Tablet",
  rating: 5,
  status: "in stock",
  description: "Macrolide antibiotic used for respiratory and skin infections.",
  reviews: [
    {
      id: "r10",
      name: "Sophia Turner",
      date: "2024-02-01",
      rating: 5,
      comment: "Highly recommend!",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia",
    },
  ],
},
{
  id: "11",
  name: "Losartan",
  price: 21,
  image: "/assets/images/shop/shopThumb1_11.jpg",
  category: "Tablet",
  rating: 4,
  status: "out of stock",
  description: "Used to treat high blood pressure and protect the kidneys.",
  reviews: [
    {
      id: "r11",
      name: "James Clark",
      date: "2024-01-30",
      rating: 4,
      comment: "Reliable medication.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    },
  ],
},
{
  id: "12",
  name: "Lisinopril",
  price: 18,
  image: "/assets/images/shop/shopThumb1_12.jpg",
  category: "Tablet",
  rating: 3,
  status: "in stock",
  description: "ACE inhibitor used to treat high blood pressure and heart failure.",
  reviews: [
    {
      id: "r12",
      name: "Olivia Harris",
      date: "2024-01-28",
      rating: 3,
      comment: "Works but mild side effects.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
    },
  ],
},
{
  id: "13",
  name: "Omeprazole",
  price: 26,
  image: "/assets/images/shop/shopThumb1_13.jpg",
  category: "Capsule",
  rating: 5,
  status: "in stock",
  description: "Proton pump inhibitor used for acid reflux and ulcers.",
  reviews: [
    {
      id: "r13",
      name: "Henry Scott",
      date: "2024-01-27",
      rating: 5,
      comment: "Relieved my reflux instantly.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry",
    },
  ],
},
{
  id: "14",
  name: "Cetirizine",
  price: 12,
  image: "/assets/images/shop/shopThumb1_14.jpg",
  category: "Tablet",
  rating: 4,
  status: "in stock",
  description: "Antihistamine used to relieve allergy symptoms.",
  reviews: [
    {
      id: "r14",
      name: "Ella Martinez",
      date: "2024-01-26",
      rating: 4,
      comment: "Helps with my allergies.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ella",
    },
  ],
},
{
  id: "15",
  name: "Hydrochlorothiazide",
  price: 17,
  image: "/assets/images/shop/shopThumb1_15.jpg",
  category: "Tablet",
  rating: 4,
  status: "in stock",
  description: "Diuretic used to treat high blood pressure and swelling.",
  reviews: [
    {
      id: "r15",
      name: "Noah Young",
      date: "2024-01-24",
      rating: 4,
      comment: "Very effective.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Noah",
    },
  ],
},
{
  id: "16",
  name: "Prednisone",
  price: 29,
  image: "/assets/images/shop/shopThumb1_16.jpg",
  category: "Tablet",
  rating: 5,
  status: "in stock",
  description: "Corticosteroid used to reduce inflammation and suppress immune system.",
  reviews: [
    {
      id: "r16",
      name: "Mia King",
      date: "2024-01-22",
      rating: 5,
      comment: "Helped reduce inflammation fast.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
    },
  ],
},
];